# Generated by Django 4.2.10 on 2024-02-21 14:03

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20240216_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to=cards.models.card_img),
        ),
        migrations.AddField(
            model_name='card',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to=cards.models.card_img),
        ),
    ]
