# Generated by Django 4.2.10 on 2024-02-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_answer_image_card_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.TextField(blank=True),
        ),
    ]
